BI-27: Test drive Search Bar
BacPacNet/web-app-client pull request #16
Opened 2023-10-25 07:06 UTC by ayushtiwari110

2023-12-07 16:15 UTC, bacpactech approved these changes

2023-12-07 19:51 UTC, ayushtiwari110 commented on src/__tests__/home.test.js
> +      name: /BacPac/i,
sure!

2023-12-07 19:53 UTC, ayushtiwari110 commented on src/__tests__/searchBar.test.js
> +})
done!

2023-12-07 19:54 UTC, ayushtiwari110 commented on src/__tests__/searchBar.test.js
> +  // console.log(screen.debug()); //For Debugging: Print the rendered component to the console
done!

2023-12-14 17:05 UTC, bacpactech requested changes

2023-12-14 17:05 UTC, bacpactech commented on .prettierignore
> +/src
Let's remove the `/src`.

2023-12-14 17:08 UTC, ayushtiwari110 commented on .prettierignore
> +/src
done!

2023-12-14 17:14 UTC, bacpactech submitted a review, later dismissed
Nicely Done! 🎉

2023-12-16 09:35 UTC, bacpactech approved these changes

2023-12-16 09:35 UTC, merged